baseURL = "https://yanpitangui.com/"
theme="archie-fork"
copyright = "© Yan Pitangui"
paginate = 5
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = 'G-2YDP77JD9X'
enableRobotsTXT = true



defaultContentLanguageInSubdir = true
DefaultContentLanguage = "pt"
[languages]
  [languages.pt]
    title = "Yan Pitangui"
    languageName = "pt"
    weight = 1
  [[languages.pt.menu.main]]
    name = "Todos os posts"
    pageRef = "/posts"
    weight = 2
  [[languages.pt.menu.main]]
    name = "Tags"
    pageRef = "/tags"
    weight = 3
  [[languages.pt.menu.main]]
    name = "Sobre mim"
    pageRef = "/about"
    weight = 4
  [languages.en]
    title = "Yan Pitangui"
    languageName = "en"
    weight = 1
  [[languages.en.menu.main]]
    name = "All posts"
    pageRef = "/posts"
    weight = 2
  [[languages.en.menu.main]]
    name = "Tags"
    pageRef = "/tags"
    weight = 3
  [[languages.en.menu.main]]
    name = "About me"
    pageRef = "/about"
    weight = 4  

[markup.goldmark.renderer]
unsafe = true

[params]
	mode="toggle"
	useCDN=true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/yanpitangui"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/aethelingaeg"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/yanpitangui/"


[permalinks]
  posts = '/posts/:year/:month/:title/'

[[menu.main]]






